version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
    container_name: backend
    ports:
      - "50051:50051"
    environment:
      - SHARED_PATH=/shared    
    volumes:
      - ./shared_files:/shared
    networks:
      - project_network

  broker_api:
    build:
      context: ./src/broker_api
    container_name: broker_api
    ports:
      - "8000:8000"
    environment:
      - SHARED_PATH=/shared
    volumes:
      - ./shared_files:/shared
    networks:
      - project_network

  scheduler:
    build:
      context: ./src/scheduler
    container_name: scheduler
    ports:
      - "8080:8080"
    depends_on:
      - broker_api
    environment:
      - SHARED_PATH=/shared 
    volumes:
      - ./shared_files:/shared      
    networks:
      - project_network

networks:
  project_network:
    driver: bridge