version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
    container_name: backend
    ports:
      - "50051:50051" # gRPC port
    environment:
      - ENV_FILE=.env
    networks:
      - project_network

  broker_api:
    build:
      context: ./src/broker_api
    container_name: broker_api
    ports:
      - "8000:8000"
    environment:
      - ENV_FILE=.env
    networks:
      - project_network

  scheduler:
    build:
      context: ./src/scheduler
    container_name: scheduler
    depends_on:
      - broker_api
    environment:
      - ENV_FILE=.env
    networks:
      - project_network

networks:
  project_network:
    driver: bridge