version: '3.9'

services:
  backend:
    build:
      context: ./src/backend
    container_name: backend
    ports:
      - "50051:50051"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SHARED_PATH=/shared
      - TZ=America/New_York
      - DB_HOST=postgres
      - DB_USER=tradeuser
      - DB_PASSWORD=tradepass
      - DB_NAME=tradedb
      - DB_PORT=5432
    volumes:
      - ./shared_files:/shared
    networks:
      - project_network
    depends_on:
      - postgres
    restart: unless-stopped

  broker_api:
    build:
      context: ./src/broker_api
    container_name: broker_api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SHARED_PATH=/shared
      - IB_HOST=ibkr
      - IB_PORT=${IB_PORT}
      - IB_CLIENT_ID=${IB_CLIENT_ID}
      - TZ=America/New_York
    volumes:
      - ./shared_files:/shared
    networks:
      - project_network
    depends_on:
      - ibkr
    restart: unless-stopped

  scheduler:
    build:
      context: ./src/scheduler
    container_name: scheduler
    ports:
      - "8080:8080"
    depends_on:
      - broker_api
      - postgres
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - SHARED_PATH=/shared 
      - TZ=America/New_York
      - DB_HOST=postgres
      - DB_USER=tradeuser
      - DB_PASSWORD=tradepass
      - DB_NAME=tradedb
      - DB_PORT=5432
    volumes:
      - ./shared_files:/shared      
    networks:
      - project_network
    restart: unless-stopped

  ibkr:
    image: ghcr.io/extrange/ibkr:stable
    container_name: ibkr
    ports:
      - "127.0.0.1:6080:6080" # noVNC browser access
      - "127.0.0.1:8888:8888" # API access
    ulimits:
      nofile: 10000
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      TZ: America/New_York
      # Configure IB Gateway instead of TWS
      GATEWAY_OR_TWS: gateway
      # Allow API connections
      IBC_ReadOnlyApi: no
      # Optional: Set trading mode (paper/live)
      IBC_TradingMode: paper
      IBC_AcceptIncomingConnectionAction: accept
      IBC_AcceptNonBrokerageAccountWarning: yes
    networks:
      - project_network
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tradeuser
      - POSTGRES_PASSWORD=tradepass
      - POSTGRES_DB=tradedb
      - POSTGRES_HOST_AUTH_METHOD=trust # Allow all connections without password
      - ENVIRONMENT=${ENVIRONMENT} # Set environment variable
      - SHARED_PATH=/shared # Set shared path
      - TZ=America/New_York # Set timezone
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project_network
    restart: unless-stopped

networks:
  project_network:
    driver: bridge

volumes:
  postgres_data:
